const CurrencyConstants = {
	UPDATE_CURRENCY: 'UPDATE_CURRENCY',
	UPDATE_CURRENCY_FAIL: 'UPDATE_CURRENCY_FAIL',
	UPDATE_YESTERDAY_CURRENCY: 'UPDATE_YESTERDAY_CURRENCY',
	UPDATE_YESTERDAY_CURRENCY_FAIL: 'UPDATE_YESTERDAY_CURRENCY_FAIL'
};

export default CurrencyConstants;
