const currencyExtraInfo = {
	EUR: { description: 'Euro', flag: 'eu' },
	AUD: { description: 'Australian dollar', flag: 'au' },
	BGN: { description: 'Bulgarian lev', flag: 'bg' },
	BRL: { description: 'Brazilian real', flag: 'br' },
	CAD: { description: 'Canadian dollar', flag: 'ca' },
	CHF: { description: 'Swiss franc', flag: 'ch' },
	CNY: { description: 'Chinese Yuan Renminbi', flag: 'cn' },
	CZK: { description: 'Czech koruna', flag: 'cz' },
	DKK: { description: 'Danish krone', flag: 'dk' },
	GBP: { description: 'British Pound', flag: 'gb' },
	HKD: { description: 'Hong Kong Dollar', flag: 'hk' },
	HRK: { description: 'Croatian kuna', flag: 'hr' },
	HUF: { description: 'Hungarian forint', flag: 'hu' },
	IDR: { description: 'Indonesian rupiah', flag: 'id' },
	ILS: { description: 'Israeli new shekel', flag: 'il' },
	INR: { description: 'Indian rupee', flag: 'in' },
	ISK: { description: 'Icelandic krona', flag: 'is' },
	JPY: { description: 'Japanese yen', flag: 'jp' },
	KRW: { description: 'South Korean won', flag: 'kr' },
	MXN: { description: 'Mexican peso', flag: 'mx' },
	MYR: { description: 'Malaysian ringgit', flag: 'my' },
	NOK: { description: 'Norwegian krone', flag: 'no' },
	NZD: { description: 'New Zealand dollar', flag: 'nz' },
	PHP: { description: 'Philippine peso', flag: 'ph' },
	PLN: { description: 'Polish zloty', flag: 'pl' },
	RON: { description: 'Romanian leu', flag: 'ro' },
	RUB: { description: 'Russian ruble', flag: 'ru' },
	SEK: { description: 'Swedish krona', flag: 'se' },
	SGD: { description: 'Singapore dollar', flag: 'sg' },
	THB: { description: 'Thai baht', flag: 'th' },
	TRY: { description: 'Turkish lira', flag: 'tr' },
	USD: { description: 'United States dollar', flag: 'us' },
	ZAR: { description: 'South African rand', flag: 'za' }
};

export default currencyExtraInfo;
