const currencyExtraInfo = {
	EUR: { description: 'Euro', flag: 'EU' },
	AUD: { description: 'Australian dollar', flag: 'AU' },
	BGN: { description: 'Bulgarian lev', flag: 'BG' },
	BRL: { description: 'Brazilian real', flag: 'BR' },
	CAD: { description: 'Canadian dollar', flag: 'CA' },
	CHF: { description: 'Swiss franc', flag: 'CH' },
	CNY: { description: 'Chinese Yuan Renminbi', flag: 'CN' },
	CZK: { description: 'Czech koruna', flag: 'CZ' },
	DKK: { description: 'Danish krone', flag: 'DK' },
	GBP: { description: 'British Pound', flag: 'GB' },
	HKD: { description: 'Hong Kong Dollar', flag: 'HK' },
	HRK: { description: 'Croatian kuna', flag: 'HR' },
	HUF: { description: 'Hungarian forint', flag: 'HU' },
	IDR: { description: 'Indonesian rupiah', flag: 'ID' },
	ILS: { description: 'Israeli new shekel', flag: 'IL' },
	INR: { description: 'Indian rupee', flag: 'IN' },
	ISK: { description: 'Icelandic krona', flag: 'IS' },
	JPY: { description: 'Japanese yen', flag: 'JP' },
	KRW: { description: 'South Korean won', flag: 'KR' },
	MXN: { description: 'Mexican peso', flag: 'MX' },
	MYR: { description: 'Malaysian ringgit', flag: 'MY' },
	NOK: { description: 'Norwegian krone', flag: 'NO' },
	NZD: { description: 'New Zealand dollar', flag: 'NZ' },
	PHP: { description: 'Philippine peso', flag: 'PH' },
	PLN: { description: 'Polish zloty', flag: 'PL' },
	RON: { description: 'Romanian leu', flag: 'RO' },
	RUB: { description: 'Russian ruble', flag: 'RU' },
	SEK: { description: 'Swedish krona', flag: 'SE' },
	SGD: { description: 'Singapore dollar', flag: 'SG' },
	THB: { description: 'Thai baht', flag: 'TH' },
	TRY: { description: 'Turkish lira', flag: 'TR' },
	USD: { description: 'United States dollar', flag: 'US' },
	ZAR: { description: 'South African rand', flag: 'ZA' }
};

export default currencyExtraInfo;
